---
##### Install zabbix-agent
  - name: ping hosts
    ping:

  - name: check OS
    debug: msg={{ansible_distribution}}-{{ansible_distribution_version}}

### centOS 7
  - name: disable SELinux
    selinux:
     state: disabled
    when: ansible_os_family == "RedHat"

  - name: install zabbix centOS 7 rpm file
    yum: name=https://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-1.el7.centos.noarch.rpm
    when: ansible_os_family == "RedHat"

  - name: install zabbix-agent 3.4 for centOS 7
    yum: 
      name: zabbix-agent
      enablerepo: zabbix
      state: latest
    when: ansible_os_family == "RedHat"

### Debian 8
  - name: download zabbix deb file for Debian 8
    get_url:
      url: https://repo.zabbix.com/zabbix/4.0/debian/pool/main/z/zabbix-release/zabbix-release_4.0-2+jessie_all.deb 
      dest: /tmp/zabbix-release_4.0-2+jessie_all.deb
    when: ansible_distribution_release == 'jessie'

  - name: install zabbix deb in Debian 8
    apt: deb="/tmp/zabbix-release_4.0-2+jessie_all.deb"
    when: ansible_distribution_release == 'jessie'

  - name: install zabbix-agent 4.0 Debian 8
    apt:
      name: zabbix-agent
      state: latest
      update_cache: yes
    when: ansible_distribution_release == 'jessie'

### Debian 9
  - name: download zabbix deb file for Debian 9
    get_url:
      url: https://repo.zabbix.com/zabbix/4.0/debian/pool/main/z/zabbix-release/zabbix-release_4.0-2+stretch_all.deb 
      dest: /tmp/zabbix-release_4.0-2+stretch_all.deb
    when: ansible_distribution_release == 'stretch'

  - name: install zabbix deb in Debian 9
    apt: deb="/tmp/zabbix-release_4.0-2+stretch_all.deb"
    when: ansible_distribution_release == 'stretch'

  - name: install zabbix-agent 4.0 Debian 9
    apt:
      name: zabbix-agent
      state: latest
      update_cache: yes
    when: ansible_distribution_release == 'stretch'

### Debian 10
  - name: download zabbix deb file for Debian 10
    get_url:
      url: https://repo.zabbix.com/zabbix/4.0/debian/pool/main/z/zabbix-release/zabbix-release_4.0-2+buster_all.deb 
      dest: /tmp/zabbix-release_4.0-2+buster_all.deb
    when: ansible_distribution_release == 'buster'

  - name: install zabbix deb in Debian 10
    apt: deb="/tmp/zabbix-release_4.0-2+buster_all.deb"
    when: ansible_distribution_release == 'buster'

  - name: install zabbix-agent 4.0 Debian 10
    apt:
      name: zabbix-agent
      state: latest
      update_cache: yes
    when: ansible_distribution_release == 'buster'

### Ubuntu 16.04 Xenial
  - name: download zabbix deb file fot Ubuntu 16.04
    get_url:
      url: https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+xenial_all.deb
      dest: /tmp/zabbix-release_4.0-2+xenial_all.deb
    when: ansible_distribution_release == 'xenial'

  - name: install zabbix deb for Ubuntu 16.04 Xenial
    apt: deb="/tmp/zabbix-release_4.0-2+xenial_all.deb"
    when: ansible_distribution_release == 'xenial'

  - name: install zabbix-agent 4.0 Ubuntu 16.04
    apt:
      name: zabbix-agent
      state: latest
      update_cache: yes
    when: ansible_distribution_release == 'xenial'


### Ubuntu 18.04 Bionic Beaver
  - name: download zabbix deb file fot Ubuntu 18.04
    get_url:
      url: https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+bionic_all.deb
      dest: /tmp/zabbix-release_4.0-2+bionic_all.deb
    when: ansible_distribution_release == 'bionic'

  - name: install zabbix deb for Ubuntu 18.04 Xenial
    apt: deb="/tmp/zabbix-release_4.0-2+bionic_all.deb"
    when: ansible_distribution_release == 'bionic'

  - name: install zabbix-agent 4.0 Ubuntu 18.04
    apt:
      name: zabbix-agent
      state: latest
      update_cache: yes
    when: ansible_distribution_release == 'bionic'

##### enabled zabbix-agent
  - name: enable service zabbix-agent and ensure it is not masked
    systemd:
      name: zabbix-agent
      enabled: yes
      masked: no
    become: yes

##### check zabbix home dir and shell
  - name: Make sure a service is stopped
    systemd: state=stopped name=zabbix-agent
    become: yes

  - name: check zabbix home dir and shell
    user:
      name: zabbix
      shell: /bin/bash
      home: /etc/zabbix
    become: yes

##### mkdir /etc/zabbix/scripts and rights
  - name: mkdir /etc/zabbix/scripts and rights
    file:
      path: /etc/zabbix/scripts
      state: directory
      owner: zabbix
      group: zabbix
      mode: 0700
    become: yes

##### change zabbix_agentd.conf
  - name: change zabbix_agentd.conf Hostname
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      state: present
      regexp: 'Hostname=Zabbix server'
      line: "Hostname={{ ansible_hostname }}"
    become: yes
    
  - name: change zabbix_agentd.conf ServerActive
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      state: present
      regexp: 'ServerActive=127.0.0.1'
      line: 'ServerActive=XXX.XXX.XXX.XXX'
    become: yes

  - name: change zabbix_agentd.conf Server
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      state: present
      regexp: 'Server=127.0.0.1'
      line: 'Server=XXX.XXX.XXX.XXX'
    become: yes

  - name: change zabbix_agentd.conf EnableRemoteCommands
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      state: present
      regexp: '# EnableRemoteCommands=0'
      line: 'EnableRemoteCommands=1'
    become: yes

  - name: change zabbix_agentd.conf LogRemoteCommands
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      state: present
      regexp: '# LogRemoteCommands=0'
      line: 'LogRemoteCommands=1'

##### Install Vulners plugin
### CentOS7
  - name: install plugin repo centOS 7 rpm file
    yum: name=https://repo.vulners.com/redhat/vulners-repo.rpm
    when: ansible_os_family == "RedHat"

  - name: install plugin for centOS 7
    yum: name=zabbix-threat-control-host
    when: ansible_os_family == "RedHat"

### Debian
  - name: download plugin deb file for Debian
    get_url:
      url: https://repo.vulners.com/debian/vulners-repo.deb
      dest: /tmp/vulners-repo.deb
    when: ansible_os_family == "Debian"

  - name: install plugin deb in Debian
    apt: deb="/tmp/vulners-repo.deb"
    when: ansible_os_family == "Debian"

  - name: install plugin Debian
    apt:
      name: zabbix-threat-control-host
      update_cache: yes
    when: ansible_os_family == "Debian"

### Starting zabbix-agent
  - name: Make sure a service is started
    systemd: state=started name=zabbix-agent
    become: yes
